landestate/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from pages import views

from django.conf import settings
from django.conf.urls.static import static
admin.site.site_title="JustEstate Project"
admin.site.site_header="JustEstate Project Administration"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("pages.urls")),
    
    path("password_reset/",auth_views.PasswordResetView.as_view(template_name="pages/password_reset.html"),name="password_reset"),
    path("password_reset_done/",auth_views.PasswordResetDoneView.as_view(template_name="pages/password_reset_sent.html"),name="password_reset_done"),
    path("password_reset_confirm/<uidb64>/<token>/",auth_views.PasswordResetConfirmView.as_view(template_name="pages/password_reset_form.html"),name="password_reset_confirm"),
    path("password_reset_complete/",auth_views.PasswordResetCompleteView.as_view(template_name="pages/password_reset_done.html"),name="password_reset_complete"),

    path("property_list_api/",views.PropertyList.as_view()),
    path("property_create_api/",views.PropertyCreate.as_view()),
    path("property_retrieve_api/<int:pk>/",views.PropertyRetrieve.as_view()),
    path("property_update_api/<int:pk>/",views.PropertyUpdate.as_view()),
    path("property_destroy_api/<int:pk>/",views.PropertyDestroy.as_view()),
    path("property_list_create_api/",views.PropertyListCreate.as_view()),
    path("property_retrieve_update_api/<int:pk>/",views.PropertyRetrieveUpdate.as_view()),
    path("property_retrieve_destroy_api/<int:pk>/",views.PropertyRetrieveDestroy.as_view()),
    path("property_retrieve_update_destroy_api/<int:pk>/",views.PropertyRetrieveUpdateDestroy.as_view()),



]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from pages import views
app_name="pages"
urlpatterns = [
    path('',views.index,name="index"),
    path('about_us/',views.about_us,name="about_us"),
    path('user_logout',views.user_logout,name="user_logout"),
    path("property_enquiry",views.property_enquiry,name="property_enquiry"),
    path("properties/",views.property_list_display,name="property_list_display"),
    path("property_details/<slug:slug>",views.property_details,name="property_details"),
    path("contact/",views.contact, name="contact"),
    path("user_login/",views.user_login,name="user_login"),
    path("registration/",views.registration,name="registration"),
    
    path("user_logout/",views.user_logout,name="user_logout"),

    path("user_details/",views.user_details,name="user_details"),
]

contact/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name=models.CharField(max_length=50)
    email=models.EmailField()
    subject=models.CharField(max_length=50)
    phone=models.CharField(max_length=12)
    message=models.TextField(max_length=500)

    def __str__(self):
        return self.name

    class Meta:
        #verbose_name = 'Contact'
        verbose_name_plural = 'Contacts'

contact/views.py
from django.shortcuts import render

# Create your views here.

templates/pages/about_us.html
{% extends 'base.html' %}
{% load static %}
{% block title %}About Us{% endblock title %}
{% block content %}

<section class="w3ls-bnrbtm py-5" style="height:900px" id="about">
    <div class="container py-xl-5 py-lg-3">
        <h3 class="title-w3 mb-md-5 mb-4 text-center text-bl font-weight-bold">Welcome To Our <span>Justestate
                Site</span></h3>
        <div class="row">
            <div class="col-lg-6 text-center">
                <img src="{% static "images/about.jpg" %}" alt="about" class="img-fluid" />
            </div>
            <div class="col-lg-6 pr-xl-5 mt-xl-4 mt-lg-0 mt-4">
                <h3 class="title-sub mb-4">The best place to find the <span>house you want.</span></h3>
                <p class="sub-para">Donec consequat sapien ut leo cursus rhoncus. Nullam dui mi, vulputate ac metus
                    at, semper
                    varius orci. Nulla accumsan ac elit in congue. Class aptent taciti sociosqu ad litora torquent
                    per conubia.</p>
                <p class="sub-para pt-4 mt-4 border-top">Donec consequat sapien ut leo cursus rhoncus. Nullam dui
                    mi, vulputate ac metus
                    at, semper varius orci. Nulla accumsan ac elit in congue. Class aptent taciti sociosqu ad
                    litora torquent per.</p>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/pages/contact.html
{% extends 'base.html' %}
{% block title %}Contacts{% endblock title %}
{% block content %}


<section class="contact" style="height:900px" id="contact" >
    <div class="container py-xl-5 py-lg-3">
        <h3 class="title-w3 mb-2 text-center text-wh font-weight-bold">Contact <span>Us</span></h3>
        <p class="text-center text-li title-w3 mb-md-5 mb-4">We are always available for your service</p>
        <div class="contact_grid_right pt-4">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% comment %} {{form.as_p}} {% endcomment %}
                 <div class="row contact_left_grid">
                    <div class="col-lg-6 con-left">
                        <div class="form-group">
                            {{form.name}}
                        </div>
                        <div class="form-group">
                            {{form.email}}
                        </div>
                        <div class="form-group">
                            {{form.subject}}
                        </div>
                    </div>
                    <div class="col-lg-6 con-right">
                        <div class="form-group">
                            {{form.message}}
                            {% comment %} <textarea id="textarea" placeholder="Message" name="Message" required=""></textarea> {% endcomment %}
                        </div>
                        <div class="input-group mb-3">
                            {{form.phone}}
                            {% comment %} <input type="file" class="form-control" name="File" id="inputGroupFile02"> {% endcomment %}
                            
                        </div>
                        
                    </div>
                </div>
                <button class="form-control btn" type="submit">Submit</button>
            </form>
        </div>
    </div>
</section>
{% endblock content %}

templates/pages/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock title %}
{% block content %}

<script>
    addEventListener("load", function () {
        setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
        window.scrollTo(0, 1);
    }
</script>
<section>
    {% include 'pages/message.html' %}
    <div class="inner-banner-w3ls py-5" style="height:900px" id="home">
        <div class="container py-xl-5 py-lg-3">
            <!-- login  -->
            <div class="modal-body my-5 pt-4">
                <h3 class="title-w3 mb-5 text-center text-wh font-weight-bold">Login Now</h3>
                <form method='post' id="loginform">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="col-form-label">Username</label>
                        <input type="text" class="form-control" placeholder="Username" name="Name" required="">
                    </div>
                    <div class="form-group">
                        <label class="col-form-label">Password</label>
                        <input type="password" class="form-control" placeholder="*****" name="Password" required="">
                    </div>

                    <button type="submit" class="btn button-style-w3 mb-3" onclick="login_validation()">Login</button>
                    
                    <p style="color:white"><strong> Dont have an account? </strong> <a class="btn btn-success" style="float:right" href="{%url "pages:registration" %}">Sign Up</a></p><br>
                    <p style="color:white"> <strong>Forgot Password?  </strong><a class="btn btn-primary" style="float:right;color:yellow" href="{%url "password_reset" %}">Reset Password</a></p>

                </form>
            </div>
            <!-- //login -->
        </div>
    </div>
</section>
{% comment %} footer {% endcomment %}
{% comment %} <footer class="py-5">
    <div class="container py-xl-4 py-lg-3">
        <div class="row footer-grids">
            <div class="col-lg-2 col-6 footer-grid">
                <h3 class="mb-sm-4 mb-3 pb-lg-3">Home</h3>
                <ul class="list-unstyled">
                    <li>
                        <a href="#">Index</a>
                    </li>
                    <li>
                        <a href="#about">About Us</a>
                    </li>
                    <li>
                        <a href="#services">Explore Properties</a>
                    </li>
                    <li>
                        <a href="#gallery">Gallery</a>
                    </li>
                    <li>
                        <a href="{% url 'pages:contact' %}">Contact Us</a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-2 col-6 footer-grid">
                <h3 class="mb-sm-4 mb-3 pb-lg-3"> Company</h3>
                <ul class="list-unstyled">
                    <li>
                        <a href="#find">Find a Property</a>
                    </li>
                    
                    <li>
                        <a href="#places">Popular Places</a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-2 col-6 footer-grid footer-contact mt-lg-0 mt-4">
                <h3 class="mb-sm-4 mb-3 pb-lg-3"> Contact Us</h3>
                <ul class="list-unstyled">
                    <li>
                        +01(24) 8543 8088
                    </li>
                    <li>
                        <a href="mailto:info@example.com">info@example.com</a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-2 col-6 footer-grid text-lg-right">
                <ul class="list-unstyled">
                    <li>
                        <a href="#facts">Statistical Facts</a>
                    </li>
                    <li>
                        <a href="#find">Find a Property</a>
                    </li>
                    <li>
                        <a href="#testi">Testimonials</a>
                    </li>
                    <li>
                        <a href="#apps">Apps</a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-4 footer-grid mt-lg-0 mt-4">
                <div class="footer-logo">
                    <h2 class="text-lg-center text-center">
                        <a class="logo text-wh font-weight-bold" href="index.html"><span
                                class="text-bl">Just</span>Estate</a>
                    </h2>
                </div>
            </div>
        </div>
    </div>
</footer> {% endcomment %}
{% endblock content %}

templates/pages/message.html
{% if messages %}
  {% for message in messages %}
    <div id="messageid" class="alert alert-dismissible alert-success">
      <button type="button" class="btn-close" data-dismiss="alert">
      </button>
      <strong>{{message}}</strong>
    </div>
 {% endfor %}
{% endif %}

templates/pages/password_reset.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <title>Reset password</title>

    <style>
        body {
            background: url(../static/images/password_reset.jpg) no-repeat center fixed; 
            background-size:cover;
          }
    </style>

  </head>
  <body>
    <section class="container-fluid" id="bgimage" >
        <h1 style="color:green">Reset Password</h1>
        <p style="font-size:20px; color:cyan">Forgot your password? Dont worry insert your registered email address below and we will contact you via email to reset your password.</p>
        <form method="POST">
            {% csrf_token %}
            <div class="row justify-content-center">
                <div class="form-control col-lg-6" >
                    {{form}}
                    <br>
                    <button type="Submit" class="btn btn-primary" Value="submit" name="Send email">Submit</button>
                </div>
            </div>
        </form>
    </section>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script>
        $("#id_email").attr({class:"form-control w-50", placeholder:"Enter Your Email"});
    </script>
  </body>
</html>

       

templates/pages/password_reset_done.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <title>Reset password</title>

    <style>
        body {
            background: url(../static/images/password_reset.jpg) no-repeat center fixed; 
            background-size:cover;
          }
    </style>

  </head>
  <body>
    <section class="container-fluid" id="bgimage" >
        <h2 style="color:orange">Password reset Complete</h2>
        <a href="/pages/userLogin"><button class="btn btn-primary">Login</button></a>
    </section>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    
  </body>
</html>

     

templates/pages/password_reset_form.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <title>Reset password</title>

    <style>
        body {
            background: url(../static/images/password_reset.jpg) no-repeat center fixed; 
            background-size:cover;
          }
    </style>

  </head>
  <body>
    <section class="container-fluid" id="bgimage" style="background-color:lightcyan">
        <h1 style="color:blue">Set New Password</h1>
        <p style="font-size:20px; color:black">Forgot your password? Dont worry insert your registered email address below and we will contact you via email to reset your password.</p>
        <div>    
            <form method="POST">
                {% csrf_token %}
                <div class="row justify-content-center">
                    <div class="form-control col-lg-6" >
                        <div class="form-group">
                            <label class="col-form-label">Password1</label><br/>
                            {{form.new_password1}}
                            
                        </div>
                        
                        <div class="form-group">
                            <label class="col-form-label">Confirm Password</label><br/>
                            {{form.new_password2}}
                            
                        </div>
                        
                        <br>
                        <button type="Submit" class="btn btn-primary" Value="submit" name="Send email">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </section>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script>
        $("#id_new_password1").attr({class:"form-control w-50", placeholder:"Enter New Password"});
        $("#id_new_password2").attr({class:"form-control w-50", placeholder:"Re-enter Password"});

    </script>
  </body>
</html>

       

templates/pages/password_reset_sent.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <title>Password sent mail</title>

    <style>
        body {
            background: url(../static/images/password_reset.jpg) no-repeat center fixed; 
            background-size:cover;
          }
    </style>

  </head>
  <body>
    <section class="container-fluid" id="bgimage" >
        <h1 style="color:green">Password reset sent</h1>
        <p style="color:cyan;font-size:20px">Password reset link has been sent to your email, Open your email and check out</p>

    </section>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    
  </body>
</html>

       
    

templates/pages/properties.html
{% extends 'base.html' %}
{% block title %}Properties{% endblock title %}

{% block content %}
    
    <section>
        <div class="w3pvtits-services py-5" id="services">
            <div class="container-fluid py-xl-5 py-lg-3">
                <h3 class="title-w3 mb-2 text-center text-wh font-weight-bold">We Provide The <span>Best Deals</span> on Properties
                </h3>
                <p style="color:white; text-align:center" >Click on the Properties below to see detailed information about it</p>
                <div class="row justify-content-center w3pvtits-services-row text-center pt-4">
                {%if page_obj%}    
                    {% for property in page_obj%}
                        <div class="col-lg-3 pt-3 pb-3 m-3 rounded border border-dark" style="background-color:lightcyan">
                            <img src="/media/{{property.photo_main}}" height="350" width="100%" alter="property"/>
                            <h4 class="text-bl my-4">{{property.title}}</h4>
                            <p class="text-left" style="color:black"> <b>Address</b>   :   <span>{{property.address}}</span></p>
                            <p class="text-left" style="color:black"> <b>City</b>   :   <span>{{property.city}}</span></p>
                            <p class="text-left" style="color:black"> <b>Description</b>   :   <span>{{property.description|safe|truncatechars:30}}</span></p>
                            <p class="text-left" style="color:black"> <b>Price</b>   :   <span>{{property.price}}</span></p>
                            <p class="text-left" style="color:black"> <b>Bedrooms</b>   :   <span>{{property.bedrooms}}</span></p>
                            <div class="container-fluid bg-success pb-3 pt-3 text-center">
                                <a class="service-btn btn btn-primary text-white" href="{% url "pages:property_details" property.slug %}">View Details</a>
                            </div>
                        </div>      
                    {% endfor %}
                    
                    {% comment %} pagination buttons {% endcomment %}
                    <div class="pagination px-3 py-3 justify-content-center">
                        <span class="step-links">
                            {% if page_obj.has_previous %}
                                <a class="btn btn-primary" href="?page=1">&laquo; first</a>
                                <a class="btn btn-primary" href="?page={{page_obj.previous_page_number }}">previous</a>
                            {% endif %}
                    
                            <span class="current text-white">
                                Page {{page_obj.number }} of {{page_obj.paginator.num_pages }}.
                            </span>
                    
                            {% if page_obj.has_next %}
                                <a class="btn btn-primary" href="?page={{page_obj.next_page_number }}">next</a>
                                <a class="btn btn-primary" href="?page={{page_obj.paginator.num_pages }}">last &raquo;</a>
                            {% endif %}
                        </span>
                    </div>
                {%elif property_list%}
        
                    {% for property in property_list%}
                    <div class="col-lg-3 pt-3 pb-3 m-3 rounded border border-dark" style="background-color:lightcyan">
                        <img src="/media/{{property.photo_main}}" height="350" width="100%" alter="property"/>
                        <h4 class="text-bl my-4">{{property.title}}</h4>
                        <p class="text-left" style="color:black"><b>Address</b>   :   <span>{{property.address}}</span></p>
                        <p class="text-left" style="color:black"><b>City</b>   :   <span>{{property.city}}</span></p>
                        <p class="text-left" style="color:black"><b>Description</b>   :   <span>{{property.description|safe|truncatechars:30}}</span></p>
                        <p class="text-left" style="color:black"><b>Price</b>   :   <span>{{property.price}}</span></p>
                        <p class="text-left" style="color:black"><b>Bedrooms</b>   :   <span>{{property.bedrooms}}</span></p>
                        <div class="container-fluid bg-success pb-3 pt-3 text-center">
                            <a class="service-btn btn btn-primary text-white" href="{% url "pages:property_details" property.slug %}">View Details</a>
                        </div>
                    </div>      
                    {% endfor %}
                
                {% comment %} pagination buttons {% endcomment %}
                    <div class="pagination px-3 py-3 justify-content-center">
                        <span class="step-links">
                            {% if property_list.has_previous %}
                                <a class="btn btn-primary" href="?page=1">&laquo; first</a>
                                <a class="btn btn-primary" href="?page={{property_list.previous_page_number }}">previous</a>
                            {% endif %}
                    
                            <span class="current text-white">
                                Page {{property_list.number }} of {{property_list.paginator.num_pages }}.
                            </span>
                    
                            {% if property_list.has_next %}
                                <a class="btn btn-primary" href="?page={{property_list.next_page_number }}">next</a>
                                <a class="btn btn-primary" href="?page={{property_list.paginator.num_pages }}">last &raquo;</a>
                            {% endif %}
                        </span>
                    </div>
                {%else%}
                    <h1 style="color:red">Sorry!! No Properties Available right now</h1>
                    
                    <h3 style="color:cyan">Feel free to Contact Us</h3>
                {%endif%}
                </div>
            </div>
            <img src="images/img.png" alt="services" class="img-fluid img-posi-w3pvt" />
        </div>
        
        
    </section>
{% endblock content %}

templates/pages/registration.html
{% extends 'base.html' %}
{% block title %} Registration {% endblock title %}
<script>
    addEventListener("load", function () {
        setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
        window.scrollTo(0, 1);
    }
</script>
{% block content %}

<section>
    <div class="inner-banner-w3ls py-5" style="height:1200px" id="home">
        <div class="container py-xl-5 py-lg-3">
            <!-- register  -->
            <div class="modal-body mt-md-2 mt-5">
                <h3 class="title-w3 mb-5 text-center text-wh font-weight-bold">Register Now</h3>
                <form method="post" enctype="multipart/form-data" action="{% url "pages:registration"%}" id="registerform">
                    {% csrf_token %}
                    

                        <div class="form-group">
                            <label class="col-form-label">First Name</label>
                            {{form.first_name}}
                        </div>
                        <div class="form-group">
                            <label class="col-form-label">Last Name</label>
                            {{form.last_name}}
                        </div>
                        <div class="form-group">
                            <label class="col-form-label">Username</label>
                            {{form.username}}
                            {% for key, errors in form.errors.items %}
                                {% for error in errors %}
                                    {% if 'username' in error %} 
                                        <div class="error">{{error}}</div>
                                    {% endif %}
                                {% endfor %}
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label class="col-form-label">Email</label>
                            {{form.email}}
                            {% for key, errors in form.errors.items %}
                            {% for error in errors %}
                                {% if 'email' in error %} 
                                <div class="error">{{error}}</div>
                                {% endif %}
                            {% endfor %}
                        {% endfor %}
                        </div>
                        <div class="form-group">
                            <label class="col-form-label">Password</label><br/>
                            {{form.password1}}
                            
                        </div>
                        <div class="form-group">
                            <label class="col-form-label">Confirm-Password</label>
                            {{form.password2}}
                            {% for key, errors in form.errors.items %}
                                {% for error in errors %}
                                    {% if 'password' in error %} 
                                    <div class="error">{{error}}</div>
                                    {% endif %}
                                {% endfor %}
                            {% endfor %}
                        </div>
                        
                  
                    <button type="submit" class="btn button-style-w3" onclick="register_validation()">Register</button>
                    {% comment %} {% if form_err %}
                        {{form_err}}
                    {%endif%} {% endcomment %}


                    <p style="color:white; margin-top:10px">Already have an account?  <a class="btn btn-primary" style="margin:auto;float:right" href="{%url "pages:user_login" %}">Sign In</a></p>

                </form>
            </div>
            <!-- //register -->
        </div>
    </div>
</section>
    
{% comment %} <footer class="py-5">
    <div class="container py-xl-4 py-lg-3">
        <div class="row footer-grids">
            <div class="col-lg-2 col-6 footer-grid">
                <h3 class="mb-sm-4 mb-3 pb-lg-3">Home</h3>
                <ul class="list-unstyled">
                    <li>
                        <a href="#">Index</a>
                    </li>
                    <li>
                        <a href="#about">About Us</a>
                    </li>
                    <li>
                        <a href="#services">Explore Properties</a>
                    </li>
                    <li>
                        <a href="#gallery">Gallery</a>
                    </li>
                    <li>
                        <a href="{% url 'pages:contact' %}">Contact Us</a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-2 col-6 footer-grid">
                <h3 class="mb-sm-4 mb-3 pb-lg-3"> Company</h3>
                <ul class="list-unstyled">
                    <li>
                        <a href="#find">Find a Property</a>
                    </li>
                    
                    <li>
                        <a href="#places">Popular Places</a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-2 col-6 footer-grid footer-contact mt-lg-0 mt-4">
                <h3 class="mb-sm-4 mb-3 pb-lg-3"> Contact Us</h3>
                <ul class="list-unstyled">
                    <li>
                        +01(24) 8543 8088
                    </li>
                    <li>
                        <a href="mailto:info@example.com">info@example.com</a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-2 col-6 footer-grid text-lg-right">
                <ul class="list-unstyled">
                    <li>
                        <a href="#facts">Statistical Facts</a>
                    </li>
                    <li>
                        <a href="#find">Find a Property</a>
                    </li>
                    <li>
                        <a href="#testi">Testimonials</a>
                    </li>
                    <li>
                        <a href="#apps">Apps</a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-4 footer-grid mt-lg-0 mt-4">
                <div class="footer-logo">
                    <h2 class="text-lg-center text-center">
                        <a class="logo text-wh font-weight-bold" href="index.html"><span
                                class="text-bl">Just</span>Estate</a>
                    </h2>
                </div>
            </div>
        </div>
    </div>
</footer> {% endcomment %}
    
{% endblock content %}